+++
title = "Design Patterns & Smells"
tags = ["gof", "patterns", "algorithms", "oop"]
+++

** notes

it seems like "design patterns" are not exclusively restricted to 'object-oriented-programming', but this is the context in which I have learned such design.

there are three main categories of Design Patterns as decreed by the 'Gang of Four'[fn:1] (the authors of a seminal work /Design Patterns | Elements of Reusable Object-Oriented Sofware/.
A. Creational Patterns
B. Structural Patterns
C. Behavioural Patterns

in turn, each of these contain more patterns:

A. Creational:
   1. Factory Method
   2. Abstract Factory
   3. Builder
   4. Prototype
   5. Singleton
B. Structural
   6. Adapter
   7. Bridge
   8. Composite
   9. Decorator
  10. Façade
  11. Flyweight
  12. Proxy
C. Behavioural:
  13. Interpreter
  14. Template method
  15. Chain of responsibility
  16. Command
  17. Iterator
  18. Mediator
  19. Memento
  20. Observer
  21. State
  22. Strategy
  23. Visitor

because these patterns tend to be solutions to bad *design smells*, I've decided to include all the details on a single page.

*** design smells

**** duplicated code


**** long method

**** large class

**** long parameter list

**** divergent change

**** shotgun surgery

**** feature envy

**** data clumps

**** primitive obsession

**** switch statements

**** parallel inheritance hierarchies

**** lazy class

**** speculative generality

**** temporary field

**** message chains

**** middle man

**** inappropriate intimacy

**** alternative classes with different interfaces

**** incomplete library class

**** data class

**** refused bequest

**** comments

comments are good, but sometimes they are used as /deoderant/ for bad code!

** Footnotes

[fn:1] Ralph Johnson, Richard Helm, Erich Gamma, and John Vlissides. 
