+++
title = "Design Patterns & Smells"
tags = ["gof", "patterns", "algorithms", "oop"]
tikzajax = "true"
math = "true"
+++

** notes

it seems like "design patterns" are not exclusively restricted to 'object-oriented-programming', but this is the context in which I have learned such design.

there are three main categories of Design Patterns as decreed by the 'Gang of Four'[fn:1] (the authors of a seminal work /Design Patterns | Elements of Reusable Object-Oriented Sofware/.


#+ATTR_HTML: :class alpha-list
#+BEGIN_LEFT
1. Creational Patterns
2. Structural Patterns
3. Behavioural Patterns
#+END_LEFT

in turn, each of these contain more patterns:

#+BEGIN_EXPORT html
<style>
/* Make the OUTER list display A., B., C. while keeping semantics numeric */
.alpha-list > ol { list-style-type: lower-alpha; }

/* Ensure nested lists keep regular decimal numbering */
.alpha-list ol ol { list-style-type: decimal; }

/* (Optional) tidy spacing */
.alpha-list ol { margin-left: 0rem; }
</style>

<div class="alpha-list">
#+END_EXPORT
1. Creational:
   1. Factory Method
   2. Abstract Factory
   3. Builder
   4. Prototype
   5. Singleton
2. Structural
   1. [@6] Adapter
   2. Bridge
   3. Composite
   4. Decorator
   5. Façade
   6. Flyweight
   7. Proxy
3. Behavioural:
   1. [@13] Interpreter
   2. Template Method
   3. Chain of Responsibility
   4. Command
   5. Iterator
   6. Mediator
   7. Memento
   8. Observer
   9. State
   10. Strategy
   11. Visitor
#+BEGIN_EXPORT html
</div>
#+END_EXPORT


because these patterns tend to be solutions to bad *design smells*, I've decided to include all the details on a single page.

*** design smells

**** duplicated code


{{< tikztwo >}}
\usepackage{tikz-uml}
\begin{document}

\begin{tikzpicture}
\begin{umlpackage}{p}
\begin{umlpackage}{sp1}
\umlclass[template=T]{A}{
  n : uint \\ t : float
}{}
\umlclass[y=-3]{B}{
  d : double
}{
  \umlvirt{setB(b : B) : void} \\ getB() : B}
\end{umlpackage}
\begin{umlpackage}[x=10,y=-6]{sp2}
\umlinterface{C}{
  n : uint \\ s : string
}{}
\end{umlpackage}
\umlclass[x=2,y=-10]{D}{
  n : uint
  }{}
\end{umlpackage}

\umlassoc[geometry=-|-, arg1=tata, mult1=*, pos1=0.3, arg2=toto, mult2=1, pos2=2.9, align2=left]{C}{B}
\umlunicompo[geometry=-|, arg=titi, mult=*, pos=1.7, stereo=vector]{D}{C}
\umlimport[geometry=|-, anchors=90 and 50, name=import]{sp2}{sp1}
\umlaggreg[arg=tutu, mult=1, pos=0.8, angle1=30, angle2=60, loopsize=2cm]{D}{D}
\umlinherit[geometry=-|]{D}{B}
\umlnote[x=2.5,y=-6, width=3cm]{B}{Je suis une note qui concerne la classe B}
\umlnote[x=7.5,y=-2]{import-2}{Je suis une note qui concerne la relation d'import}
\end{tikzpicture}

\end{document}

{{< /tikztwo >}}

**** long method

**** large class

**** long parameter list

**** divergent change

**** shotgun surgery

**** feature envy
:PROPERTIES:
:CUSTOM_ID: feature-envy
:END:


**** data clumps

**** primitive obsession

**** switch statements

**** parallel inheritance hierarchies

**** lazy class

**** speculative generality

**** temporary field

**** message chains

**** middle man

**** inappropriate intimacy

**** alternative classes with different interfaces

**** incomplete library class

**** data class

**** refused bequest

**** comments

comments are good, but sometimes they are used as /deoderant/ for bad code!

** Footnotes

[fn:1] Ralph Johnson, Richard Helm, Erich Gamma, and John Vlissides. 
