This blog post has been created to convince you that real-world
probability, is in fact _Bayesian_ probability.

Anyone who believes that a frequentist approach is superior may be
correct (for that particular example), but it must be said that the
Bayesian framework is a superset of this naive and trivial
card-playing model of probability.

We are no longer trying to determine the probability of landing a
`double-six` dice roll, and rather we are trying to figure out what
the probability is that Mia (our cat) will be waiting for us on the
porch when we get home.

* History (optional)
It starts with Cardano, leads to Pascal and Leibniz. Makes its way to
*insert russian dude*, blah blah blah.

* The Crux of the Matter
Prior. That is the crux. What is the probability Mia will be waiting
on the chair on the porch? Well that depends on a few things: is it
raining? did we feed her before we left? is it really hot? did she get
into another cat fight?

Each of these questions, either answered or unanswered influence the
probability.

Formally we have P(Mia on Red Chair) =

* Comparisons

** Physical Examples

** Meta-Physical Examples
The nature of the matter is that black-box, infinitely sampling from
this black box, etc. Thus superset.
