+++
title = "Elisp Notes"
tags = ["notes", "gnu", "emacs"]
+++

I remember when using Emacs itself was a huge struggle for me. But now I have just =sudo apt install emacs='d this vanilla install and I am already off to the races.

Anyways, I'll probably slim down this prose at a later date when I find it cringe and too verbose; but for now I am having a terrific time thwacking away at a [[drunkdeer.com/products/drunkdeer-a75-pro-wired-actuation-distance-adjustable-magnetic-switch-keyboard][Drunkdeer A75 Pro]] (thanks Aarav).

I've opted to scribble here as opposed to in a =README= this time.

#+BEGIN_SRC shell
  │  ~/.config  sudo apt install emacs-common-non-dfsg
#+END_SRC

for some reason getting the =info= entry working for "An Introduction to Programming in Emacs Lisp" was a little more involved than it should have been. Anyways, just run the above command and the compressed =.info.gz= files should be downloaded.

* Info: An Introduction to Programming in Emacs Lisp

** 1. Lisp Lists

#+BEGIN_QUOTE
It is better to refer to Emacs as an "extensible computing environment".
#+END_QUOTE

Lisp was first developed in the late 1950s at the Massachusetts
Institute of Technology for research in artificial intelligence.

Emacs Lisp is much simpler than Common Lisp

Lots of Isolated Silly Parentheses

In Lisp, both data and programs are represented the same way

In a list, atoms are separated from each other by whitespace.  They
can be right next to a parenthesis.

- when a quote (') is preceeding a list, then it tells Lisp to do _nothing_ with the list.
  - i.e. (+ 2 2) will evaluate to 4 with =C-x C-e=, but
  - '(this is a quoted list) will not interpret the first "atom" as an instruction.

=if=, =defun=, =when=.

the interpreter works left to right, from one expression
to the next.

you can byte-compile emacs lisp! extension is =.elc=.


- when a quote (') is preceeding a list, then it tells Lisp to do _nothing_ with the list.
  - i.e. (+ 2 2) will evaluate to 4 with =C-x C-e=, but
  - '(this is a quoted list) will not interpret the first "atom" as an instruction.

=if=, =defun=, =when=.

the interpreter works left to right, from one expression
to the next.

you can byte-compile emacs lisp! extension is =.elc=.

#+BEGIN_SRC lisp
     (message "He saw %d %s"
              (- fill-column 32)
              (concat "red "
                      (substring
                       "The quick brown foxes jumped." 16 21)
                      " leaping."))
#+END_SRC

#+BEGIN_SRC lisp
     (setq trees '(pine fir oak maple)
           herbivores '(gazelle antelope zebra))
#+END_SRC

#+BEGIN_SRC lisp
     (setq counter 0)                ; Let's call this the initializer.

     (setq counter (+ counter 1))    ; This is the incrementer.

     counter                         ; This is the counter.
#+END_SRC

- numbers and strings are literals and evaluate to themselves.
- a function always returns a value when it is evaluated (unless error).
  - the func can also carry out an action as a side-effect. often times this is the primary purpose.

** 2. Practising Evaluation

Whenever you give an editing command to Emacs Lisp, such as the command
to move the cursor or to scroll the screen, you are evaluating an
expression, the first element of which is a function.  This is how Emacs
works.

In Lisp, ‘nil’ is also used to mean "false" and is a synonym for the empty list, '()'.

#+BEGIN_SRC lisp
(concat "this buffer is called " (buffer-name) " with file-name " (buffer-file-name))
#+END_SRC

buffer != file.

#+BEGIN_SRC lisp
  (current-buffer)
  (other-buffer) ; that which you cannot see
  (switch-to-buffer (other-buffer))
  (buffer-size) ;3766
  (point) ;3696
  (point-min)
  (- (point-max) (point-min)) ; == (buffer-size)
#+END_SRC

** 3. Writing Defuns

Let me re-emphasize this: when you write code in Emacs Lisp, you do
not distinguish between the use of functions written in C and the use of
functions written in Emacs Lisp.  The difference is irrelevant.

#+BEGIN_SRC lisp
  (defun multiply-by-seven (number) ; interactive
    "multiplies a number by seven" ;seen when you call this with `C-h f`
    (interactive "p") ; "p" means pass the prefix argument to the function.
    (message "The result is %d" (* 7 number)))
  (multiply-by-seven 6)
#+END_SRC
(mark-whole-buffer)

** 4. Buffer Walk Through

** 5. More Complex

** 
