---
title: "Bday Problems"
date: 2024-12-15T11:19:55+11:00
draft: false
toc: true
math: true
layout: single
---

{{< collapse folded="true">}}
Each year I release a set of problems to celebrate yet another year of life and study. On this page you will find the embedded Problem Sets, a submission [[/projects/bday-problems#link][link]] and the [[/projects/bday-problems#winners][List of Past Winners]].

** [[/projects/bday-problems/24th][24th]]
:PROPERTIES:
:CUSTOM_ID: 24th
:END:

As is tradition, the prize pool has increased (to $300 this year).

I have collapsed first and second place into a winner-takes-all arrangement (c'est la vie).

Furthermore, there are additional changes to the structure of this Game:
1. you must now *pass* the problem set to be awarded the prize money
2. you may submit your solutions to the problem set at any point in the future -- hopefully your children are smart enough to solve these problems
3. if you plagiarise work, I reserve the right to ban you from all subsequent competitions --- /[[https://en.wikipedia.org/wiki/Grim_trigger][grim trigger]]/
4. the problem set will now be courteously supported by my JavaScript \(\LaTeX\) engine and a PDF will be generated as an artifact of the site;
   - the problems can be found [[/projects/bday-problems/24th/problems][here]] or as a [[/doc/bday-problems/24th.pdf][PDF]] [[/projects/bday-problems/24th/problems][here]]
   - my solutions will be available from the start of 2026; by viewing them you *forfeit the prize money* (obviously)
5. Good luck!

** [[/projects/bday-problems/23rd][23rd]]
:PROPERTIES:
:CUSTOM_ID: 23rd
:END:

The prize money shall be $150 for first place and $100 for second.

*ERRATA:*
- The matrix A in question 15b /is/ symmetric.

Here is the problem set:

{{< embed-pdf url="/bday-problems/23q.pdf" hidePaginator="true">}}

** [[/projects/bday-problems/22nd][22nd]]
:PROPERTIES:
:CUSTOM_ID: 22nd
:END:

{{< embed-pdf url="/bday-problems/22q.pdf" hidePaginator="true">}}

** [[/projects/bday-problems/21st][21st]]
:PROPERTIES:
:CUSTOM_ID: 21st
:END:

{{< embed-pdf url="/bday-problems/21q.pdf" hidePaginator="true">}}

** [[/projects/bday-problems/upload][Submission Link]]
:PROPERTIES:
:CUSTOM_ID: link
:END:
The heading /is/ the link :p

** List of Winners
:PROPERTIES:
:CUSTOM_ID: winners
:END:

- Aarav Bajaj
- Jisu Song
- Sarro Aghrel
- Erick Rajan 
